In [1]:
import polars as pl

In [2]:
pl.__version__

'1.37.1'

In [4]:
# Read files
green_taxi_2025 = pl.read_parquet("data/green_tripdata_2025-11.parquet")

In [6]:
zones = pl.read_csv("data/taxi_zone_lookup.csv")

In [5]:
green_taxi_2025.head()

shape: (5, 21)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ payment_t ┆ trip_type ┆ congestio ┆ cbd_conge │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ ype       ┆ ---       ┆ n_surchar ┆ stion_fee │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ i64       ┆ ge        ┆ ---       │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ i64       ┆           ┆ ---       ┆ f64       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆ f64       ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:34:48  ┆ 00:41:39  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 2         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:18:52  ┆ 00:24:27  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 01:03:14  ┆ 01:15:24  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 0.0       ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:10:57  ┆ 00:24:53  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 1         ┆ 2.75      ┆ 0.0       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 00:03:48  ┆ 00:19:38  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [7]:
zones.head()

shape: (5, 4)
┌────────────┬───────────────┬─────────────────────────┬──────────────┐
│ LocationID ┆ Borough       ┆ Zone                    ┆ service_zone │
│ ---        ┆ ---           ┆ ---                     ┆ ---          │
│ i64        ┆ str           ┆ str                     ┆ str          │
╞════════════╪═══════════════╪═════════════════════════╪══════════════╡
│ 1          ┆ EWR           ┆ Newark Airport          ┆ EWR          │
│ 2          ┆ Queens        ┆ Jamaica Bay             ┆ Boro Zone    │
│ 3          ┆ Bronx         ┆ Allerton/Pelham Gardens ┆ Boro Zone    │
│ 4          ┆ Manhattan     ┆ Alphabet City           ┆ Yellow Zone  │
│ 5          ┆ Staten Island ┆ Arden Heights           ┆ Boro Zone    │
└────────────┴───────────────┴─────────────────────────┴──────────────┘

In [8]:
zones.shape

(265, 4)

In [9]:
green_taxi_2025.shape

(46912, 21)

In [23]:
# Add column pickup datetime
green_taxi_2025 = green_taxi_2025.with_columns(
    pl.col("lpep_pickup_datetime").dt.date().alias("pickup_date")
)

In [32]:
# Filter out rows with date 2025-12-01
green_taxi_2025 = green_taxi_2025.filter(
    pl.col("pickup_date") != pl.datetime(2025,12,1)
)

green_taxi_2025

shape: (46_899, 22)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ trip_type ┆ congestio ┆ cbd_conge ┆ pickup_da │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ ---       ┆ n_surchar ┆ stion_fee ┆ te        │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ i64       ┆ ge        ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆           ┆ ---       ┆ f64       ┆ date      │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆ f64       ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 0.0       ┆ 0.0       ┆ 2025-11-0 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│          ┆ 00:34:48  ┆ 00:41:39  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 0.0       ┆ 0.0       ┆ 2025-11-0 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│          ┆ 00:18:52  ┆ 00:24:27  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 0.0       ┆ 0.0       ┆ 2025-11-0 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│          ┆ 01:03:14  ┆ 01:15:24  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 0.0       ┆ 0.0       ┆ 2025-11-0 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│          ┆ 00:10:57  ┆ 00:24:53  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 1        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 1         ┆ 2.75      ┆ 0.0       ┆ 2025-11-0 │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆ 1         │
│          ┆ 00:03:48  ┆ 00:19:38  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 2025-11-3 │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 0         │
│          ┆ 19:58:34  ┆ 20:14:28  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 2025-11-3 │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 0         │
│          ┆ 19:34:00  ┆ 19:46:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.75      ┆ 2025-11-3 │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 0         │
│          ┆ 21:46:46  ┆ 22:17:55  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ 2025-11-3 │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 0         │
│          ┆ 21:00:00  ┆ 21:15:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ null      ┆ null      ┆ 0.75      ┆ 2025-11-3 │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆           ┆ 0         │
│          ┆ 23:26:00  ┆ 23:42:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Question 3. Counting short trips 
#### For the trips in November 2025, how many trips had a trip_distance of less than or equal to 1 mile?

In [37]:
# Question 3. For the trips in November 2025, how many trips had a trip_distance of less than or equal to 1 mile?
green_taxi_2025.filter(pl.col("trip_distance") <= 1).select(pl.len())

shape: (1, 1)
┌──────┐
│ len  │
│ ---  │
│ u32  │
╞══════╡
│ 8007 │
└──────┘

## Question 4. Longest trip for each day
#### Which was the pick up day with the longest trip distance? Only consider trips with trip_distance less than 100 miles (to exclude data errors). Use the pick up time for your calculations.

In [62]:
green_taxi_2025 \
    .filter(pl.col("trip_distance") < 100) \
    .group_by("pickup_date") \
    .agg(
        pl.col("trip_distance").max().alias("max_trip_distance")
    ) \
    .sort("max_trip_distance", descending=True) \
    .head(1)

shape: (1, 2)
┌─────────────┬───────────────────┐
│ pickup_date ┆ max_trip_distance │
│ ---         ┆ ---               │
│ date        ┆ f64               │
╞═════════════╪═══════════════════╡
│ 2025-11-14  ┆ 88.03             │
└─────────────┴───────────────────┘

## Question 5. Biggest pickup zone

#### Which was the pickup zone with the largest total_amount (sum of all trips) on November 18th, 2025?

In [63]:
green_taxi_2025_joined = green_taxi_2025.join(zones, left_on="PULocationID", right_on="LocationID")
green_taxi_2025_joined

shape: (46_899, 25)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ pickup_da ┆ Borough   ┆ Zone      ┆ service_z │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ te        ┆ ---       ┆ ---       ┆ one       │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ date      ┆           ┆           ┆ str       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 2025-11-0 ┆ Manhattan ┆ East      ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆ 1         ┆           ┆ Harlem    ┆           │
│          ┆ 00:34:48  ┆ 00:41:39  ┆           ┆   ┆           ┆           ┆ North     ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 2025-11-0 ┆ Manhattan ┆ East      ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆ 1         ┆           ┆ Harlem    ┆           │
│          ┆ 00:18:52  ┆ 00:24:27  ┆           ┆   ┆           ┆           ┆ North     ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 2025-11-0 ┆ Queens    ┆ Elmhurst/ ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆ 1         ┆           ┆ Maspeth   ┆           │
│          ┆ 01:03:14  ┆ 01:15:24  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 2025-11-0 ┆ Manhattan ┆ Morningsi ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆ 1         ┆           ┆ de        ┆           │
│          ┆ 00:10:57  ┆ 00:24:53  ┆           ┆   ┆           ┆           ┆ Heights   ┆           │
│ 1        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ 2025-11-0 ┆ Manhattan ┆ Morningsi ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆ 1         ┆           ┆ de        ┆           │
│          ┆ 00:03:48  ┆ 00:19:38  ┆           ┆   ┆           ┆           ┆ Heights   ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ 2025-11-3 ┆ Bronx     ┆ Crotona   ┆ Boro Zone │
│          ┆ 0         ┆ 0         ┆           ┆   ┆ 0         ┆           ┆ Park      ┆           │
│          ┆ 19:58:34  ┆ 20:14:28  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ 2025-11-3 ┆ Manhattan ┆ East      ┆ Boro Zone │
│          ┆ 0         ┆ 0         ┆           ┆   ┆ 0         ┆           ┆ Harlem    ┆           │
│          ┆ 19:34:00  ┆ 19:46:00  ┆           ┆   ┆           ┆           ┆ North     ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ 2025-11-3 ┆ Brooklyn  ┆ Brooklyn  ┆ Boro Zone │
│          ┆ 0         ┆ 0         ┆           ┆   ┆ 0         ┆           ┆ Heights   ┆           │
│          ┆ 21:46:46  ┆ 22:17:55  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ 2025-11-3 ┆ Queens    ┆ Bayside   ┆ Boro Zone │
│          ┆ 0         ┆ 0         ┆           ┆   ┆ 0         ┆           ┆           ┆           │
│          ┆ 21:00:00  ┆ 21:15:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ 2025-11-3 ┆ Brooklyn  ┆ Downtown  ┆ Boro Zone │
│          ┆ 0         ┆ 0         ┆           ┆   ┆ 0         ┆           ┆ Brooklyn/ ┆           │
│          ┆ 23:26:00  ┆ 23:42:00  ┆           ┆   ┆           ┆           ┆ MetroTech ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [70]:
green_taxi_2025_joined \
    .filter(pl.col("pickup_date") == pl.datetime(2025,11,18)) \
    .group_by("Zone") \
    .agg(
        pl.col("fare_amount").sum().alias("amount")
    ) \
    .sort("amount", descending=True) \
    .head(1)

shape: (1, 2)
┌───────────────────┬─────────┐
│ Zone              ┆ amount  │
│ ---               ┆ ---     │
│ str               ┆ f64     │
╞═══════════════════╪═════════╡
│ East Harlem North ┆ 6555.32 │
└───────────────────┴─────────┘

## Question 6. Largest tip

#### For the passengers picked up in the zone named "East Harlem North" in November 2025, which was the drop off zone that had the largest tip? Note: it's tip , not trip. We need the name of the zone, not the ID.

In [75]:
harlem_north_pickups = green_taxi_2025_joined \
    .filter(pl.col("Zone") == "East Harlem North")

harlem_north_pickups.select(pl.len())

shape: (1, 1)
┌───────┐
│ len   │
│ ---   │
│ u32   │
╞═══════╡
│ 12042 │
└───────┘

In [78]:
harlem_north_dropoffs = harlem_north_pickups.join(zones, left_on="DOLocationID", right_on="LocationID")
harlem_north_dropoffs

shape: (12_042, 28)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ VendorID ┆ lpep_pick ┆ lpep_drop ┆ store_and ┆ … ┆ service_z ┆ Borough_r ┆ Zone_righ ┆ service_z │
│ ---      ┆ up_dateti ┆ off_datet ┆ _fwd_flag ┆   ┆ one       ┆ ight      ┆ t         ┆ one_right │
│ i32      ┆ me        ┆ ime       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆ ---       ┆ ---       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
│          ┆ datetime[ ┆ datetime[ ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ μs]       ┆ μs]       ┆           ┆   ┆           ┆           ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ Boro Zone ┆ Manhattan ┆ Central   ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ Harlem    ┆           │
│          ┆ 00:34:48  ┆ 00:41:39  ┆           ┆   ┆           ┆           ┆ North     ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ Boro Zone ┆ Manhattan ┆ Central   ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ Harlem    ┆           │
│          ┆ 00:18:52  ┆ 00:24:27  ┆           ┆   ┆           ┆           ┆ North     ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ Boro Zone ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ East      ┆ Zone      │
│          ┆ 00:38:13  ┆ 00:55:47  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-0 ┆ 2025-11-0 ┆ N         ┆ … ┆ Boro Zone ┆ Manhattan ┆ East      ┆ Boro Zone │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆ Harlem    ┆           │
│          ┆ 00:20:44  ┆ 00:27:05  ┆           ┆   ┆           ┆           ┆ North     ┆           │
│ 2        ┆ 2025-10-3 ┆ 2025-11-0 ┆ N         ┆ … ┆ Boro Zone ┆ Unknown   ┆ NA        ┆ N/A       │
│          ┆ 1         ┆ 1         ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 23:58:40  ┆ 00:26:34  ┆           ┆   ┆           ┆           ┆           ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ Boro Zone ┆ Manhattan ┆ Manhattan ┆ Yellow    │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ Valley    ┆ Zone      │
│          ┆ 16:50:21  ┆ 17:08:49  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ Boro Zone ┆ Manhattan ┆ Yorkville ┆ Yellow    │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ West      ┆ Zone      │
│          ┆ 16:15:00  ┆ 16:27:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ Boro Zone ┆ Bronx     ┆ Morrisani ┆ Boro Zone │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ a/Melrose ┆           │
│          ┆ 16:26:00  ┆ 16:44:00  ┆           ┆   ┆           ┆           ┆           ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ Boro Zone ┆ Manhattan ┆ Lincoln   ┆ Yellow    │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ Square    ┆ Zone      │
│          ┆ 18:31:00  ┆ 18:52:00  ┆           ┆   ┆           ┆           ┆ East      ┆           │
│ 2        ┆ 2025-11-3 ┆ 2025-11-3 ┆ null      ┆ … ┆ Boro Zone ┆ Manhattan ┆ Manhattan ┆ Yellow    │
│          ┆ 0         ┆ 0         ┆           ┆   ┆           ┆           ┆ Valley    ┆ Zone      │
│          ┆ 19:34:00  ┆ 19:46:00  ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [80]:
harlem_north_dropoffs \
    .group_by("Zone_right") \
    .agg(
        pl.col("tip_amount").max().alias("max_tip_amount")
    ) \
    .sort("max_tip_amount", descending=True)

shape: (137, 2)
┌───────────────────────────────┬────────────────┐
│ Zone_right                    ┆ max_tip_amount │
│ ---                           ┆ ---            │
│ str                           ┆ f64            │
╞═══════════════════════════════╪════════════════╡
│ Yorkville West                ┆ 81.89          │
│ LaGuardia Airport             ┆ 50.0           │
│ East Harlem North             ┆ 45.0           │
│ Long Island City/Queens Plaza ┆ 34.25          │
│ NA                            ┆ 28.9           │
│ …                             ┆ …              │
│ South Ozone Park              ┆ 0.0            │
│ Gowanus                       ┆ 0.0            │
│ Van Cortlandt Village         ┆ 0.0            │
│ Chinatown                     ┆ 0.0            │
│ Forest Park/Highland Park     ┆ 0.0            │
└───────────────────────────────┴────────────────┘